/** Major Indian cities offered as autocomplete suggestions for pickup/destination fields. */
export const INDIAN_CITIES: string[] = [
  'Mumbai', 'Delhi', 'Bengaluru', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune',
  'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna',
  'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Kalyan',
  'Varanasi', 'Srinagar', 'Aurangabad', 'Dhanbad', 'Amritsar', 'Navi Mumbai', 'Allahabad', 'Ranchi',
  'Howrah', 'Coimbatore', 'Jabalpur', 'Gwalior', 'Vijayawada', 'Jodhpur', 'Madurai', 'Raipur',
  'Kota', 'Chandigarh', 'Guwahati', 'Solapur', 'Hubli-Dharwad', 'Mysuru', 'Tiruchirappalli',
  'Bareilly', 'Aligarh', 'Tiruppur', 'Gurugram', 'Moradabad', 'Jalandhar', 'Bhubaneswar', 'Salem',
  'Warangal', 'Guntur', 'Bhiwandi', 'Saharanpur', 'Gorakhpur', 'Bikaner', 'Amravati', 'Noida',
  'Jamshedpur', 'Bhilai', 'Cuttack', 'Firozabad', 'Kochi', 'Nellore', 'Bhavnagar', 'Dehradun',
  'Durgapur', 'Asansol', 'Rourkela', 'Nanded', 'Kolhapur', 'Ajmer', 'Akola', 'Gulbarga', 'Jamnagar',
  'Ujjain', 'Loni', 'Siliguri', 'Jhansi', 'Ulhasnagar', 'Jammu', 'Sangli-Miraj', 'Mangaluru',
  'Erode', 'Belgaum', 'Ambattur', 'Tirunelveli', 'Malegaon', 'Gaya', 'Udaipur', 'Kakinada',
  'Davanagere', 'Kozhikode', 'Rajahmundry', 'Bokaro', 'Thiruvananthapuram', 'Agartala',
  'Bilaspur', 'Bhagalpur', 'Muzaffarnagar', 'Bhatpara', 'Panipat', 'Darbhanga', 'Bally', 'Aizawl',
  'Dewas', 'Ichalkaranji', 'Karnal', 'Bathinda', 'Jalgaon', 'Eluru', 'Kirari Suleman Nagar',
  'Barasat', 'Purnia', 'Satna', 'Mau', 'Sonipat', 'Farrukhabad', 'Sagar', 'Durg',
  'Imphal', 'Ratlam', 'Hapur', 'Anantapur', 'Arrah', 'Karimnagar', 'Etawah', 'Ambernath', 'North Dumdum',
  'Bharatpur', 'Begusarai', 'New Delhi', 'Gandhinagar', 'Baranagar', 'Tirupati', 'Puducherry',
  'Karawal Nagar', 'Mahbubnagar', 'Dindigul', 'Shillong', 'Ozhukarai', 'Nandyal', 'Morena',
  'Bhiwani', 'Porbandar', 'Palakkad', 'Anand', 'Purulia', 'Baharampur', 'Barmer', 'Morbi',
  'Panchkula', 'Raichur', 'Silchar', 'Ongole', 'Nagercoil', 'Thanjavur', 'Vellore', 'Alwar',
  'Bihar Sharif', 'Bardhaman', 'Kulti', 'Kavali', 'Sirsa', 'Alappuzha', 'Bidar', 'Chapra',
  'Guntakal', 'Yamunanagar', 'Gandhidham', 'Adoni', 'Motihari', 'Khammam', 'Puri', 'Baripada',
  'Shimla', 'Manali', 'Rishikesh', 'Haridwar', 'Mussoorie', 'Nainital', 'Darjeeling', 'Gangtok',
  'Munnar', 'Alleppey', 'Ooty', 'Kodaikanal', 'Mount Abu', 'Goa', 'Panaji', 'Margao', 'Pushkar',
  'Mahabaleshwar', 'Lonavala', 'Coorg', 'Wayanad', 'Leh', 'Manesar', 'Digha', 'Mahabalipuram',
  'Khajuraho', 'Hampi', 'Pondicherry', 'Kasol', 'Dharamshala', 'McLeodganj', 'Auli', 'Kufri',
];
